- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Set SSL permissions
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: '/etc/nginx/ssl/nginx.key', owner: 'root', group: 'root', mode: '0600' }
    - { path: '/etc/nginx/ssl/nginx.crt', owner: 'root', group: 'root', mode: '0644' }
  notify: Restart Nginx
  