---
# tasks file for php
- name: Install PHP 8.1 and required extensions
  ansible.builtin.apt:
    name:
      - php8.1-fpm
      - php8.1-mysql
      - php8.1-xml
      - php8.1-mbstring
      - php8.1-gd
      - php8.1-curl
      - php8.1-zip
    state: present
    update_cache: yes

- name: Start and enable PHP-FPM service
  ansible.builtin.service:
    name: php8.1-fpm
    state: started
    enabled: true
