---
# tasks file for php
- name: Install PHP 8.1 and required extensions
  ansible.builtin.apt:
    name:
      - php8.1-fpm
      - php8.1-mysql
      - php8.1-xml
      - php8.1-mbstring
      - php8.1-gd
      - php8.1-curl
      - php8.1-zip
    state: present
    update_cache: true

- name: Configure PHP-FPM to use nginx user
  ansible.builtin.template:
    src: www.conf.j2
    dest: /etc/php/8.1/fpm/pool.d/www.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart PHP-FPM

- name: Start and enable PHP-FPM service
  ansible.builtin.service:
    name: php8.1-fpm
    state: started
    enabled: true
