- name: Create Docker volume for aaPanel
  community.docker.docker_volume:
    name: aapanel_data
    state: present

- name: Run aaPanel container
  community.docker.docker_container:
    name: aapanel
    image: aapanel/aapanel
    state: started
    restart_policy: always
    published_ports:
      - "8888:7800"
    volumes:
      - aapanel_data:/www/wwwroot

- name: Wait for aaPanel container to exist and be running
  community.docker.docker_container_info:
    name: aapanel
  register: aapanel_info
  until: aapanel_info.exists and aapanel_info.containers | length > 0 and aapanel_info.containers[0].State.Status == 'running'
  retries: 20
  delay: 5

- name: Update _COOKIE_PATH in common.py inside container
  community.docker.docker_container_exec:
    container: aapanel
    command: sed -i "s|_COOKIE_PATH = '/'|_COOKIE_PATH = '/aapanel/'|" /www/server/panel/class/common.py
    user: root

- name: Update _panel_path in common.py inside container
  community.docker.docker_container_exec:
    container: aapanel
    command: sed -i "s|_panel_path = '/'|_panel_path = '/aapanel/'|" /www/server/panel/class/common.py
    user: root

- name: Restart aaPanel inside container
  community.docker.docker_container_exec:
    container: aapanel
    command: /etc/init.d/bt restart
    user: root

- name: Restart nginx on host
  ansible.builtin.systemd:
    name: nginx
    state: restarted
