- name: Clear Nginx error log for fresh start
  ansible.builtin.command: sudo truncate -s 0 /var/log/nginx/error.log
  changed_when: false
  failed_when: false

- name: Create Docker volume for aaPanel
  community.docker.docker_volume:
    name: aapanel_data
    state: present
  register: aapanel_docker_volume_result

- name: Debug check Docker volume creation
  ansible.builtin.debug:
    msg: "Docker volume 'aapanel_data' created. Changed status: {{ aapanel_docker_volume_result.changed }}"

- name: Run aaPanel container
  community.docker.docker_container:
    name: aapanel
    image: aapanel/aapanel
    state: started
    restart_policy: always
    published_ports:
      - "8888:7800"
    env:
      PANEL_PORT: "7800"
      PANEL_DOMAIN: "{{ ansible_host }}"
      PANEL_BASE: "/"
    volumes:
      - aapanel_data:/www/wwwroot
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:7800 || exit 1"]
      interval: 10s
      retries: 5
  register: aapanel_docker_container_result
  notify: Restart Nginx

- name: Wait for aaPanel container to be healthy
  community.docker.docker_container_info:
    name: aapanel
  register: aapanel_info
  until: aapanel_info.container is defined and aapanel_info.container.State.Health.Status == 'healthy'
  retries: 20
  delay: 5

- name: Wait for aaPanel service to be ready internally
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}:8889"
    status_code: 200,301,302
    timeout: 5
  register: aapanel_service_ready
  until: aapanel_service_ready is succeeded
  retries: 20
  delay: 5

- name: Pause to allow Nginx to restart
  ansible.builtin.pause:
    seconds: 15

- name: Ensure aaPanel data directory exists
  community.docker.docker_container_exec:
    container: aapanel
    command: mkdir -p /www/server/panel/data
    user: root

- name: Wait for aaPanel to be accessible via Nginx proxy
  ansible.builtin.uri:
    url: "https://127.0.0.1:8889"
    validate_certs: false
    follow_redirects: all
    status_code: 200,301,302
    timeout: 5
  register: aapanel_local_result
  until: aapanel_local_result is succeeded
  retries: 20
  delay: 10
  delegate_to: "{{ inventory_hostname }}"

- name: Debug final access info
  ansible.builtin.debug:
    msg: "aaPanel доступний за https://{{ ansible_host }}:8889"
