- name: Create Docker volume for aaPanel
  community.docker.docker_volume:
    name: aapanel_data
    state: present

- name: Run aaPanel container
  community.docker.docker_container:
    name: aapanel
    image: aapanel/aapanel:latest
    state: started
    restart_policy: unless-stopped
    ports:
      - "8888:7800"
    volumes:
      - aapanel_data:/www
