- name: Create Docker volume for aaPanel
  community.docker.docker_volume:
    name: aapanel_data
    state: present

- name: Run aaPanel container
  community.docker.docker_container:
    name: aapanel
    image: aapanel/aapanel
    state: started
    restart_policy: always
    published_ports:
      - "8888:7800"
    volumes:
      - aapanel_data:/www/wwwroot

- name: Wait for aaPanel container to be running
  community.docker.docker_container_info:
    name: aapanel
  register: aapanel_info
  until: aapanel_info.container is defined and aapanel_info.container.State.Status == 'running'
  retries: 20
  delay: 5

- name: Update _COOKIE_PATH in common.py inside container
  community.docker.docker_container_exec:
    container: aapanel
    command: sed -i "s|_COOKIE_PATH = '/'|_COOKIE_PATH = '/aapanel/'|" /www/server/panel/class/common.py
    user: root

- name: Update _panel_path in common.py inside container
  community.docker.docker_container_exec:
    container: aapanel
    command: sed -i "s|_panel_path = '/'|_panel_path = '/aapanel/'|" /www/server/panel/class/common.py
    user: root

- name: Restart aaPanel inside container
  community.docker.docker_container_exec:
    container: aapanel
    command: /etc/init.d/bt restart
    user: root

- name: Restart nginx on host
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Wait for aaPanel web service to be responsive via proxy
  ansible.builtin.uri:
    url: https://127.0.0.1/aapanel/
    validate_certs: false
    follow_redirects: all
    status_code: [200, 302]
  register: aapanel_result
  until: aapanel_result.status == 200 or aapanel_result.status == 302
  retries: 20
  delay: 10
  delegate_to: "{{ inventory_hostname }}"
