- name: Create Docker volume for aaPanel
  community.docker.docker_volume:
    name: aapanel_data
    state: present

- name: Run aaPanel container
  community.docker.docker_container:
    name: aapanel
    image: aapanel/aapanel
    state: started
    restart_policy: always
    published_ports:
      - "8080:80"    # HTTP внутрішній → 8080 на хості
      - "8443:443"   # HTTPS внутрішній → 8443 на хості
      - "8888:7800"  # aaPanel веб-інтерфейс
    volumes:
      - "{{ ansible_user_dir }}/aapanel_data:/www/wwwroot"
