- name: Create Docker volume for aaPanel
  community.docker.docker_volume:
    name: aapanel_data
    state: present

- name: Run aaPanel container
  community.docker.docker_container:
    name: aapanel
    image: aapanel/aapanel
    state: started
    restart_policy: always
    published_ports:
      - "8888:7800"
    volumes:
      - aapanel_data:/www/wwwroot

- name: Wait for aaPanel container to be running
  community.docker.docker_container_info:
    name: aapanel
  register: aapanel_info
  until: aapanel_info.container is defined and aapanel_info.container.State.Status == 'running'
  retries: 20
  delay: 5

- name: Set aaPanel panel_path to /aapanel inside container
  community.docker.docker_container_exec:
    container: aapanel
    command: echo "/aapanel" > /www/server/panel/data/panel_path.pl
    user: root

- name: Restart aaPanel inside container
  community.docker.docker_container_exec:
    container: aapanel
    command: /etc/init.d/bt restart
    user: root

- name: Check panel_path.pl content inside container
  community.docker.docker_container_exec:
    container: aapanel
    command: cat /www/server/panel/data/panel_path.pl
  register: panel_path_check
  delegate_to: "{{ inventory_hostname }}"

- name: Display panel_path.pl content
  ansible.builtin.debug:
    var: panel_path_check.stdout_lines

- name: Restart nginx on host
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Wait for aaPanel web service to be responsive via proxy
  ansible.builtin.uri:
    url: https://127.0.0.1/aapanel/
    validate_certs: false
    follow_redirects: all
  register: aapanel_result
  until: aapanel_result.status == 200
  retries: 20
  delay: 10
  delegate_to: "{{ inventory_hostname }}"
