- name: Create Docker volume for aaPanel
  community.docker.docker_volume:
    name: aapanel_data
    state: present
  register: aapanel_docker_volume_result

- name: Debug check Docker volume creation
  ansible.builtin.debug:
    msg: "Docker volume 'aapanel_data' created. Changed status: {{ aapanel_docker_volume_result.changed }}"

- name: Create Docker network for aapanel
  community.docker.docker_network:
    name: aapanel_net
    state: present

- name: Run aaPanel container
  community.docker.docker_container:
    name: aapanel
    image: aapanel/aapanel
    state: started
    restart_policy: always
    networks:
      - name: aapanel_net
    env:
      PANEL_PORT: "7800"
      PANEL_DOMAIN: "{{ ansible_host }}"
      PANEL_BASE: "/"
    volumes:
      - aapanel_data:/www/wwwroot

  register: aapanel_docker_container_result
  notify: Restart Nginx

- name: Wait for aaPanel container to be healthy
  community.docker.docker_container_info:
    name: aapanel
  register: aapanel_info
  until: aapanel_info.container is defined and aapanel_info.container.State.Health.Status == 'healthy'
  retries: 20
  delay: 5

- name: Ensure aaPanel data directory exists
  community.docker.docker_container_exec:
    container: aapanel
    command: mkdir -p /www/server/panel/data
    user: root

- name: Wait for aaPanel to be accessible locally (container + Nginx proxy)
  ansible.builtin.uri:
    url: "https://127.0.0.1:8889/login"
    validate_certs: false
    follow_redirects: all
    status_code: 200, 301, 302
    connect_timeout: 5
  register: aapanel_local_result
  until: aapanel_local_result.status in [200, 301, 302]
  retries: 20
  delay: 10
  delegate_to: "{{ inventory_hostname }}"

- name: Wait for aaPanel to be accessible externally (GitHub runner → EC2)
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}:8889/login"
    validate_certs: false
    follow_redirects: all
    status_code: 200, 301, 302
    connect_timeout: 5
  register: aapanel_external_result
  until: aapanel_external_result.status in [200, 301, 302]
  retries: 20
  delay: 10
  delegate_to: localhost

- name: Debug final access info
  ansible.builtin.debug:
    msg: |
      aaPanel доступний локально (через Nginx) на 127.0.0.1:8889
      aaPanel доступний зовні за https://{{ ansible_host }}:8889
