- name: Create Docker volume for aaPanel
  community.docker.docker_volume:
    name: aapanel_data
    state: present

- name: Run aaPanel container
  community.docker.docker_container:
    name: aapanel
    image: aapanel/aapanel
    state: started
    restart_policy: always
    ports:
      - "80:80"      # Дозволяє aaPanel керувати HTTP
      - "443:443"    # Дозволяє aaPanel керувати HTTPS
      - "8888:7800"  # Дозволяє доступ до панелі на порту 8888, якщо 80/443 зайняті
    volumes:
      - "{{ ansible_user_dir }}/aapanel_data:/www/wwwroot"
