---
- name: Deploy WordPress on EC2
  hosts: webservers
  become: true

  vars:
    db_name: "wordpress_db"
    db_user: "wordpress_user"
    wordpress_site_path: "/var/www/html/wordpress"

  vars_files:
    - secrets.yml

  roles:
    - role: common
    - role: mariadb
    - role: nginx
    - role: php
    - role: wordpress
    - role: docker
    - role: aapanel
