---
- name: Deploy WordPress on EC2
  hosts: webservers
  become: true

  vars:
    db_name: "wordpress_db"
    db_user: "wordpress_user"
    wordpress_site_path: "/var/www/html"

  vars_files:
    - secrets.yml
  pre_tasks:
    - name: Create nginx user and group
      ansible.builtin.user:
        name: nginx
        state: present
        system: true
        home: /var/www
        shell: /sbin/nologin

  roles:
    - role: mariadb
    - role: nginx
    - role: php
    - role: wordpress
    - role: docker
    - role: aapanel

  post_tasks:
    - name: Clear Nginx error log for fresh start
      ansible.builtin.command: sudo truncate -s 0 /var/log/nginx/error.log
      changed_when: false
      failed_when: false
