name: Destroy WordPress on EC2

on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    name: "Destroy EC2 with Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ALLOWED_IPS: ${{ secrets.ALLOWED_IPS }}
      AWS_KEY_NAME: ${{ secrets.AWS_KEY_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init with S3 Backend
        run: |
          terraform init \
            -backend-config="bucket=my-first-remote-state" \
            -backend-config="key=nginx/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=terraform-locks"
        working-directory: terraform

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
            -var "allowed_ips=${ALLOWED_IPS}" \
            -var "key_name=${{ env.AWS_KEY_NAME }}"
        working-directory: terraform
        env:
          ALLOWED_IPS: ${{ secrets.ALLOWED_IPS }}
          AWS_KEY_NAME: ${{ secrets.AWS_KEY_NAME }}
