name: Destroy WordPress on EC2

on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    name: "Destroy EC2 with Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ALLOWED_IPS: ${{ secrets.ALLOWED_IPS }}
      AWS_KEY_NAME: ${{ secrets.AWS_KEY_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init -lock=false
        working-directory: terraform

      - name: Terraform Destroy
        run: | 
          terraform destroy -auto-approve -lock=false \
            -var "allowed_ips=${ALLOWED_IPS}" \
            -var "key_name=${AWS_KEY_NAME}"
        working-directory: terraform
