name: Test on Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'ansible/**'
      - '.github/workflows/**'
      - 'README.md'

jobs:
  terraform_validate_wordpress:
    name: "Terraform Validate (WordPress)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      - name: Terraform Init
        run: terraform init
        working-directory: terraform/wordpress
      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/wordpress

  terraform_validate_plesk:
    name: "Terraform Validate (Plesk)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      - name: Terraform Init
        run: terraform init
        working-directory: terraform/plesk
      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/plesk

  terraform_plan_wordpress:
    name: "Terraform Plan (WordPress)"
    runs-on: ubuntu-latest
    needs: [terraform_validate_wordpress]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ALLOWED_IPS: ${{ secrets.ALLOWED_IPS }}
      AWS_KEY_NAME: ${{ secrets.AWS_KEY_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      - name: Terraform Init
        run: terraform init
        working-directory: terraform/wordpress
      - name: Terraform Plan
        run: |
          terraform plan \
            -var "allowed_ips=${{ env.ALLOWED_IPS }}" \
            -var "key_name=${{ env.AWS_KEY_NAME }}"
        working-directory: terraform/wordpress

  terraform_plan_plesk:
    name: "Terraform Plan (Plesk)"
    runs-on: ubuntu-latest
    needs: [terraform_validate_plesk]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ALLOWED_IPS: ${{ secrets.ALLOWED_IPS }}
      AWS_KEY_NAME: ${{ secrets.AWS_KEY_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      - name: Terraform Init
        run: terraform init
        working-directory: terraform/plesk
      - name: Terraform Plan
        run: |
          terraform plan \
            -var "allowed_ips=${{ env.ALLOWED_IPS }}" \
            -var "key_name=${{ env.AWS_KEY_NAME }}"
        working-directory: terraform/plesk

  ansible_lint:
    name: "Ansible Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible ansible-lint
      - name: Run Ansible Lint
        run: ansible-lint ansible/wordpress_deploy.yml