name: Test on Dev Branch (Simulated Deploy)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'ansible/**'
      - '.github/workflows/**'
      - 'README.md'

jobs:
  terraform_validate:
    name: "Terraform Validate"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      - name: Terraform Init (no backend)
        run: terraform init -backend=false
        working-directory: terraform
      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

  terraform_plan_sim:
    name: "Terraform Plan Simulation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      - name: Terraform Init (no backend)
        run: terraform init -backend=false
        working-directory: terraform
      - name: Terraform Plan Dry-run
        run: terraform plan -refresh=false \
          -var "allowed_ips=0.0.0.0/0" \
          -var "key_name=dummy-key"
        working-directory: terraform

  ansible_lint:
    name: "Ansible Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible ansible-lint
      - name: Lint Playbook
        run: ansible-lint ansible/wordpress_deploy.yml
